import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  { ignores: ['dist'] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ['**/*.{ts,tsx}'],
    languageOptions: { ecmaVersion: 2022, globals: globals.browser },
    plugins: { 'react-hooks': reactHooks, 'react-refresh': reactRefresh },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
    },
  },
  {
    // Machine-generated by img2threejs (scripts/generate-threejs-model.sh) and regenerated per
    // build pass. Its correctness gate is the render review, not lint, and every rule it trips is
    // inherent to generated code: a @ts-nocheck header because the generator does not target this
    // project's noUncheckedIndexedAccess, and `any` in its own spec-blob types. Code that USES
    // these factories is linted and type-checked normally.
    files: ['src/game/rendering/models/generated/**/*.ts'],
    rules: {
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
);
