#!/usr/bin/env bash
# Run the img2threejs factory generator for one model and adopt its output into the repo.
#
#   scripts/generate-threejs-model.sh <spec.json> <out.ts> <pass-id>
#
# The generator emits code written against plain `tsc`, not against this project's
# `noUncheckedIndexedAccess`, so every `array[i]` in it reads as possibly-undefined here. The file
# is machine-generated and regenerated per build pass — nobody edits it — and its correctness gate
# is the render review, not the type checker, so it is adopted with a checked-in opt-out header
# rather than hand-patched. Code that *uses* the factory is fully type-checked as normal.
set -euo pipefail

SKILL="${IMG2THREEJS_SKILL:-$HOME/.claude/skills/img2threejs}"
SPEC="$1"; OUT="$2"; PASS="$3"

python3 "$SKILL/forge/stage3_build/generate_threejs_factory.py" "$SPEC" --out "$OUT" --pass-id "$PASS" --force

HEADER="// Generated by img2threejs from $(basename "$(dirname "$SPEC")")/object-sculpt-spec.json (pass: $PASS).
// Do not edit: rerun scripts/generate-threejs-model.sh instead. Reconstruction decisions live in
// the spec, never only here.
// @ts-nocheck"
printf '%s\n%s' "$HEADER" "$(cat "$OUT")" > "$OUT.tmp" && mv "$OUT.tmp" "$OUT"
echo "adopted $OUT"
